# sample config defaults file
epochs:
  desc: Number of epochs to train over
  value: 100
batch_size:
  desc: Size of each mini-batch
  value: 10
optimizer:
  desc: Optimizer name (Adam or AdamW)
  value: AdamW
learning_rate:
  desc: Learning rate for optimizer
  value: 0.001
embedding_size: 
  desc: Size of embeddings to use
  value: 512
same_label_multiplier: 
  desc:  Multiplier for same label embedding pairs in contrastive loss
  value: 5
num_labels:
  desc: Number of labels (2, 3, or 6)
  value: 3